export interface ILogin {
  email: string;
  password: string;
}
export interface IUserDB {
  id: number;
  email: string;
  password: string;
}

export interface IUserSingUp {
  email: string;
  password: string;
  confirmPassword: string;
}
export interface IGuest {
  id: number;
  createdAt: Date;
  fullName: string;
  email: string;
  nationalId: string;
  natioanality: string;
  countryFlag: string;
}
export interface IBooking {
  id: number;
  createdAt: Date;
  startDate: Date;
  endDate: Date;
  numNights: number;
  numGuests: number;
  cabinPrice: number;
  extrasPrice: number;
  totalPrice: number;
  status: string;
  hasBreakFast: boolean;
  isPaid: boolean;
  observation: boolean;
  cabinId: number;
  guestId: number;
}

export interface ICabin {
  id: number;
  createdAt: Date;
  name: string;
  maxCapacity: number;
  regularPrice: number;
  discount: number;
  description: string;
}
/*
create table
  public.bookings (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    "startDate" timestamp without time zone null,
    "endDate" timestamp without time zone null,
    "numNights" smallint null,
    "numGuests" smallint null,
    "cabinPrice" real null,
    "extrasPrice" real null,
    "totalPrice" real null,
    status text null,
    "hasBreakfast" boolean null,
    "isPaid" boolean null,
    observations text null,
    "cabinId" bigint null,
    "guestId" bigint null,
    constraint bookings_pkey primary key (id),
    constraint bookings_cabinId_fkey foreign key ("cabinId") references cabins (id),
    constraint bookings_guestId_fkey foreign key ("guestId") references guests (id)
  ) tablespace pg_default;

  create table
  public.cabins (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    "maxCapacity" smallint null,
    "regularPrice" smallint null,
    discount smallint null,
    description text null,
    constraint cabins_pkey primary key (id)
  ) tablespace pg_default;
*/
